-- 코드를 입력하세요
SELECT R.REST_ID, R.REST_NAME, R.FOOD_TYPE, R.FAVORITES, R.ADDRESS, S.SCORE
FROM REST_INFO R
JOIN (SELECT REST_ID, ROUND(AVG(REVIEW_SCORE),2)  AS SCORE FROM REST_REVIEW GROUP BY REST_ID) AS S 
ON R.REST_ID = S.REST_ID
WHERE ADDRESS LIKE "서울%"
ORDER BY SCORE DESC, FAVORITES DESC